apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "30"
  name: mongos-router-external-service
  namespace: develop
  labels:
    name: mongos-router-external
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    role: mongos-router
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
